INSERT INTO OWNER (FIRSTNAME, LASTNAME) VALUES ('JOHN', 'TRAVOLTA');


INSERT INTO ADVERT (NAME, PRICE, CURRENCY, DESCRIPTION, QUANTITY, OWNER_ID) VALUES ('SPACE SHIP', 2000, 'SEK', 'TestFest', 1, 1);
INSERT INTO ADVERT (NAME, PRICE, CURRENCY, DESCRIPTION, QUANTITY) VALUES ('SPACE SHIP2', 3000, 'SEK', 'testParty', 1);


