INSERT INTO OWNER (FIRSTNAME, LASTNAME) VALUES ('Vincent', 'Vega');
INSERT INTO OWNER (FIRSTNAME, LASTNAME) VALUES ('Marcellus', 'Wallace');
INSERT INTO OWNER (FIRSTNAME, LASTNAME) VALUES ('Kathy', 'Sierra');


INSERT INTO ADVERT (NAME, PRICE, CURRENCY, DESCRIPTION, QUANTITY, OWNER_ID) VALUES ('A Space ship', 2000, 'SEK', 'It can fly', 1, 1);
INSERT INTO ADVERT (NAME, PRICE, CURRENCY, DESCRIPTION, QUANTITY, OWNER_ID) VALUES ('Matrix trilogy', 599, 'SEK', 'First movie is the best', 1, 2);
INSERT INTO ADVERT (NAME, PRICE, CURRENCY, DESCRIPTION, QUANTITY, OWNER_ID) VALUES ('Head first java', 400, 'SEK', 'Java for beginners', 1, 3);


