CREATE TABLE ADVERT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  PRICE INT NOT NULL,
  DESCRIPTION VARCHAR(64) NOT NULL,
  CURRENCY VARCHAR(64) NOT NULL,
  QUANTITY INT NULL
);